# Generated by Django 4.2.27 on 2026-01-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('url', 'URL'), ('email', 'Email')], max_length=10)),
                ('input_data', models.TextField()),
                ('risk_score', models.FloatField(default=0.0)),
                ('verdict', models.CharField(choices=[('safe', 'Safe'), ('suspicious', 'Suspicious'), ('phishing', 'Phishing')], default='safe', max_length=20)),
                ('explanation', models.TextField(blank=True)),
                ('indicators', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
